# Generated by Django 6.0 on 2025-12-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="license_image",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
