# Generated by Django 6.0 on 2025-12-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_license_image"),
    ]

    operations = []
