# Generated by Django 4.2 on 2026-02-08 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_predictionresult_notification_doctorvalidation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="prediction",
        ),
        migrations.AddField(
            model_name="notification",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="receiver_role",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("doctor", "Doctor"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
