# Generated by Django 4.2 on 2026-02-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_remove_notification_doctor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image_size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
