# Generated by Django 4.2 on 2026-02-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_retinalimage_selected_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorvalidation",
            name="digital_signature",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
