# Generated by Django 4.2 on 2026-03-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_doctorvalidation_digital_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorvalidation",
            name="report_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
