# Generated by Django 4.2 on 2026-03-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_doctorvalidation_report_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="target_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_page",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
