# Generated by Django 4.2 on 2026-03-05 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_notification_target_id_notification_target_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_role",
                    models.CharField(
                        choices=[("patient", "Patient"), ("doctor", "Doctor")],
                        max_length=10,
                    ),
                ),
                ("medical_conditions", models.JSONField(blank=True, null=True)),
                ("vision_symptoms", models.JSONField(blank=True, null=True)),
                ("additional_notes", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_details",
                        to="accounts.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_details",
                        to="accounts.patient",
                    ),
                ),
            ],
        ),
    ]
