# Generated by Django 4.2 on 2026-03-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_medicaldetails"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicaldetails",
            options={
                "verbose_name": "Medical Detail",
                "verbose_name_plural": "Medical Details",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
