# Generated by Django 4.2 on 2026-03-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_medicaldetails_options_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_code_expire",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
