# Generated by Django 4.2 on 2026-03-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_user_reset_code_user_reset_code_expire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="reset_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
